import { SHEET_LAYOUTS } from './sheets';
import type { SheetSchema } from '../types';

const LOG_TOOLING = {
  allowedOperations: ['read', 'insert', 'update'],
  allowedSelectors: ['date', 'date-range', 'recent', 'row-number'],
} as const;

const ENTITY_TOOLING = {
  allowedOperations: ['read', 'insert', 'update'],
  allowedSelectors: ['recent', 'row-number'],
} as const;

const READ_ONLY_TOOLING = {
  allowedOperations: ['read'],
  allowedSelectors: ['date', 'date-range', 'recent', 'row-number'],
} as const;

const AUTO_GENERATED = {
  tooling: {
    autoGenerated: true,
  },
} as const;

const IMMUTABLE = {
  tooling: {
    immutable: true,
  },
} as const;

export const SHEET_SCHEMAS = {
  STATUS_LOG: {
    name: SHEET_LAYOUTS.STATUS_LOG.name,
    idPrefix: 'status',
    tooling: LOG_TOOLING,
    fields: [
      { key: 'entry_id', type: 'string', required: true, ...AUTO_GENERATED },
      { key: 'logged_at', type: 'timestamp', required: true, ...IMMUTABLE },
      {
        key: 'occurred_at',
        type: 'timestamp',
        required: true,
        description: 'When the status event actually happened.',
      },
      {
        key: 'entry_type',
        type: 'enum',
        required: true,
        enumValues: ['bowel', 'menstruation', 'symptom', 'medication'],
        description:
          'Status category: bowel movement, menstruation, symptom, or medication.',
      },
      {
        key: 'value',
        type: 'string-or-number',
        required: true,
        description:
          'Primary recorded value. For menstruation, use a short status such as light, medium, or heavy bleeding rather than copying the full user sentence.',
      },
      {
        key: 'unit',
        type: 'string',
        required: false,
        description: 'Unit only when value is numeric, such as mg or times.',
      },
      {
        key: 'note',
        type: 'string',
        required: false,
        description:
          'Optional extra detail that does not fit in the main value.',
      },
      {
        key: 'cycle_day',
        type: 'number',
        required: false,
        description: 'Menstrual cycle day number, such as 3 for 经期第3天.',
      },
    ],
  },
  BODY_LOG: {
    name: SHEET_LAYOUTS.BODY_LOG.name,
    idPrefix: 'body',
    tooling: LOG_TOOLING,
    fields: [
      {
        key: 'body_log_id',
        type: 'string',
        required: true,
        ...AUTO_GENERATED,
      },
      { key: 'logged_at', type: 'timestamp', required: true, ...IMMUTABLE },
      {
        key: 'occurred_at',
        type: 'timestamp',
        required: true,
        description: 'When the body measurement happened.',
      },
      {
        key: 'weight_kg',
        type: 'number',
        required: false,
        description: 'Body weight in kilograms.',
      },
      {
        key: 'bmi',
        type: 'number',
        required: false,
        description: 'Body mass index.',
      },
      {
        key: 'body_fat_pct',
        type: 'number',
        required: false,
        description: 'Body fat percentage.',
      },
      {
        key: 'lean_body_mass_kg',
        type: 'number',
        required: false,
        description: 'Lean body mass in kilograms.',
      },
      {
        key: 'source',
        type: 'enum',
        required: true,
        enumValues: ['manual', 'ios_health', 'smart_scale'],
        description: 'Where the body measurement came from.',
      },
      {
        key: 'note',
        type: 'string',
        required: false,
        description: 'Optional extra context about the measurement.',
      },
    ],
  },
  SLEEP_LOG: {
    name: SHEET_LAYOUTS.SLEEP_LOG.name,
    idPrefix: 'sleep',
    tooling: LOG_TOOLING,
    fields: [
      {
        key: 'sleep_log_id',
        type: 'string',
        required: true,
        ...AUTO_GENERATED,
      },
      { key: 'logged_at', type: 'timestamp', required: true, ...IMMUTABLE },
      { key: 'sleep_start_at', type: 'timestamp', required: true },
      { key: 'sleep_end_at', type: 'timestamp', required: true },
      { key: 'sleep_hours', type: 'number', required: false },
      {
        key: 'sleep_quality',
        type: 'enum',
        required: true,
        enumValues: ['good', 'normal', 'poor'],
      },
      {
        key: 'source',
        type: 'enum',
        required: true,
        enumValues: ['manual', 'ios_health', 'smart_scale'],
      },
      { key: 'note', type: 'string', required: false },
    ],
  },
  WORKOUT_LOG: {
    name: SHEET_LAYOUTS.WORKOUT_LOG.name,
    idPrefix: 'workout',
    tooling: LOG_TOOLING,
    fields: [
      {
        key: 'workout_id',
        type: 'string',
        required: true,
        ...AUTO_GENERATED,
      },
      { key: 'logged_at', type: 'timestamp', required: true, ...IMMUTABLE },
      { key: 'occurred_at', type: 'timestamp', required: true },
      { key: 'workout_name', type: 'string', required: true },
      { key: 'workout_video_url', type: 'string', required: false },
      {
        key: 'workout_level',
        type: 'enum',
        required: true,
        enumValues: ['easy', 'medium', 'hard'],
      },
      { key: 'duration_min', type: 'number', required: false },
      { key: 'avg_hr', type: 'number', required: false },
      { key: 'max_hr', type: 'number', required: false },
      { key: 'min_hr', type: 'number', required: false },
      { key: 'calories_kcal', type: 'number', required: false },
      { key: 'note', type: 'string', required: false },
    ],
  },
  FOOD_LOG: {
    name: SHEET_LAYOUTS.FOOD_LOG.name,
    idPrefix: 'food',
    tooling: LOG_TOOLING,
    fields: [
      {
        key: 'food_log_id',
        type: 'string',
        required: true,
        ...AUTO_GENERATED,
      },
      { key: 'logged_at', type: 'timestamp', required: true, ...IMMUTABLE },
      {
        key: 'occurred_at',
        type: 'timestamp',
        required: true,
        description: 'When the meal or snack happened.',
      },
      {
        key: 'meal_type',
        type: 'enum',
        required: true,
        enumValues: ['breakfast', 'lunch', 'dinner', 'snack'],
        description: 'Canonical meal slot.',
      },
      {
        key: 'meal_text',
        type: 'string',
        required: true,
        description: 'Short description of what was eaten.',
      },
      { key: 'calories_kcal', type: 'number', required: false },
      { key: 'protein_g', type: 'number', required: false },
      { key: 'fat_g', type: 'number', required: false },
      { key: 'carbs_g', type: 'number', required: false },
      { key: 'vegetable_g', type: 'number', required: false },
      { key: 'linked_food_ref_ids', type: 'string', required: false },
      { key: 'linked_stock_item_ids', type: 'string', required: false },
      { key: 'note', type: 'string', required: false },
    ],
  },
  STOCK: {
    name: SHEET_LAYOUTS.STOCK.name,
    idPrefix: 'stock',
    tooling: ENTITY_TOOLING,
    fields: [
      {
        key: 'stock_item_id',
        type: 'string',
        required: true,
        ...AUTO_GENERATED,
      },
      { key: 'item_name', type: 'string', required: true },
      { key: 'quantity', type: 'number', required: false },
      { key: 'unit', type: 'string', required: false },
      { key: 'purchased_at', type: 'timestamp', required: false },
      { key: 'updated_at', type: 'timestamp', required: false },
      { key: 'purchase_channel', type: 'string', required: false },
      { key: 'linked_food_ref_id', type: 'string', required: false },
      { key: 'note', type: 'string', required: false },
    ],
  },
  REF_CALORIES: {
    name: SHEET_LAYOUTS.REF_CALORIES.name,
    idPrefix: 'ref',
    tooling: ENTITY_TOOLING,
    fields: [
      {
        key: 'food_ref_id',
        type: 'string',
        required: true,
        ...AUTO_GENERATED,
      },
      { key: 'food_name', type: 'string', required: true },
      { key: 'brand', type: 'string', required: false },
      { key: 'serving_size', type: 'number', required: false },
      { key: 'serving_unit', type: 'string', required: false },
      { key: 'calories_kcal', type: 'number', required: false },
      { key: 'protein_g', type: 'number', required: false },
      { key: 'fat_g', type: 'number', required: false },
      { key: 'carbs_g', type: 'number', required: false },
      {
        key: 'source',
        type: 'enum',
        required: true,
        enumValues: [
          'nutrition_label',
          'manual_entry',
          'internet_reference',
          'ai_estimate',
        ],
      },
      { key: 'updated_at', type: 'timestamp', required: true, ...IMMUTABLE },
      { key: 'note', type: 'string', required: false },
    ],
  },
  BOT_LOG: {
    name: SHEET_LAYOUTS.BOT_LOG.name,
    tooling: READ_ONLY_TOOLING,
    fields: [
      {
        key: 'logged_at',
        type: 'timestamp',
        required: true,
        validator: 'timestamp-with-milliseconds',
        ...IMMUTABLE,
      },
      { key: 'raw_text', type: 'string', required: true },
      { key: 'final_reply', type: 'string', required: true },
      {
        key: 'handling_mode',
        type: 'enum',
        required: true,
        enumValues: ['command', 'rule', 'ai'],
      },
      {
        key: 'status',
        type: 'enum',
        required: true,
        enumValues: ['success', 'ignored', 'failed'],
      },
      { key: 'trace_id', type: 'string', required: false },
      { key: 'tool_call_count', type: 'number', required: false },
      { key: 'read_count', type: 'number', required: false },
      { key: 'insert_count', type: 'number', required: false },
      { key: 'update_count', type: 'number', required: false },
      { key: 'read_sheet_names', type: 'string', required: false },
      { key: 'write_sheet_names', type: 'string', required: false },
      { key: 'primary_action', type: 'string', required: false },
      { key: 'primary_target_sheet', type: 'string', required: false },
      { key: 'primary_selector_type', type: 'string', required: false },
      { key: 'primary_selector_value', type: 'string', required: false },
      { key: 'changed_fields', type: 'string', required: false },
      { key: 'action_summary', type: 'string', required: false },
      { key: 'result_code', type: 'string', required: false },
      { key: 'note', type: 'string', required: false },
    ],
  },
} satisfies Record<keyof typeof SHEET_LAYOUTS, SheetSchema>;
