import { describe, expect, it } from 'vitest';

import type { FieldToolingSchema } from '../types';
import { SHEET_SCHEMAS } from './sheet-schema';

function getFieldTooling(
  schema: (typeof SHEET_SCHEMAS)[keyof typeof SHEET_SCHEMAS],
  key: string,
): FieldToolingSchema | undefined {
  const field = schema.fields.find((candidate) => candidate.key === key);

  if (!field || !('tooling' in field)) {
    return undefined;
  }

  return field.tooling;
}

describe('sheet schema tooling metadata', () => {
  it('marks log-style tables as full generic-tool tables with id prefixes', () => {
    expect(SHEET_SCHEMAS.FOOD_LOG.idPrefix).toBe('food');
    expect(SHEET_SCHEMAS.FOOD_LOG.tooling).toEqual({
      allowedOperations: ['read', 'insert', 'update'],
      allowedSelectors: ['date', 'date-range', 'recent', 'row-number'],
    });

    expect(SHEET_SCHEMAS.STATUS_LOG.idPrefix).toBe('status');
    expect(SHEET_SCHEMAS.STATUS_LOG.tooling.allowedSelectors).toEqual([
      'date',
      'date-range',
      'recent',
      'row-number',
    ]);
  });

  it('marks generated identifiers and immutable timestamps explicitly', () => {
    expect(getFieldTooling(SHEET_SCHEMAS.BODY_LOG, 'body_log_id')).toEqual({
      autoGenerated: true,
    });
    expect(getFieldTooling(SHEET_SCHEMAS.BODY_LOG, 'logged_at')).toEqual({
      immutable: true,
    });
    expect(getFieldTooling(SHEET_SCHEMAS.BODY_LOG, 'occurred_at')).toBe(
      undefined,
    );

    expect(getFieldTooling(SHEET_SCHEMAS.REF_CALORIES, 'food_ref_id')).toEqual({
      autoGenerated: true,
    });
    expect(getFieldTooling(SHEET_SCHEMAS.REF_CALORIES, 'updated_at')).toEqual({
      immutable: true,
    });
  });

  it('keeps stock timestamps editable for user correction and stock refresh', () => {
    expect(getFieldTooling(SHEET_SCHEMAS.STOCK, 'purchased_at')).toBe(
      undefined,
    );
    expect(getFieldTooling(SHEET_SCHEMAS.STOCK, 'updated_at')).toBe(undefined);
  });

  it('keeps bot log read-only for generic tools in v1', () => {
    expect(SHEET_SCHEMAS.BOT_LOG.tooling).toEqual({
      allowedOperations: ['read'],
      allowedSelectors: ['date', 'date-range', 'recent', 'row-number'],
    });
  });
});
