export type FieldSchemaType =
  | 'string'
  | 'number'
  | 'timestamp'
  | 'enum'
  | 'string-or-number';

export type ToolOperation = 'read' | 'insert' | 'update';

export type ToolSelectorType = 'date' | 'date-range' | 'recent' | 'row-number';

export type FieldToolingSchema = {
  autoGenerated?: boolean;
  immutable?: boolean;
};

export type SheetToolingSchema = {
  allowedOperations: readonly ToolOperation[];
  allowedSelectors: readonly ToolSelectorType[];
};

export type FieldSchema = {
  key: string;
  type: FieldSchemaType;
  required: boolean;
  enumValues?: readonly string[];
  description?: string;
  validator?: string;
  tooling?: FieldToolingSchema;
};

export type SheetSchema = {
  name: string;
  idPrefix?: string;
  tooling: SheetToolingSchema;
  fields: readonly FieldSchema[];
};
