type AppConfig = {
  SHEET_ID: string;
  BOT_TOKEN: string;
  MY_CHAT_ID: string;
};

declare const __APP_CONFIG__: AppConfig;

export const SHEET_ID = __APP_CONFIG__.SHEET_ID;
export const BOT_TOKEN = __APP_CONFIG__.BOT_TOKEN;
export const MY_CHAT_ID = __APP_CONFIG__.MY_CHAT_ID;

export const SHEETS_NAMES = {
  STATUS_LOG: 'Status_Log',
  BODY_LOG: 'Body_Log',
  SLEEP_LOG: 'Sleep_Log',
  WORKOUT_LOG: 'Workout_Log',
  FOOD_LOG: 'Food_Log',
  FOOD_ITEMS: 'Food_Items',
  STOCK: 'Stock',
  REF_CALORIES: 'Ref_Calories',
  BOT_LOG: 'Bot_Log',
} as const;

export const SHEET_LAYOUTS = {
  STATUS_LOG: {
    name: SHEETS_NAMES.STATUS_LOG,
    fields: [
      'entry_id',
      'logged_at',
      'entry_type',
      'value',
      'unit',
      'note',
      'cycle_day',
    ],
    headers: [
      '记录ID(entry_id)',
      '记录时间(logged_at)',
      '记录类型(entry_type)',
      '数值(value)',
      '单位(unit)',
      '备注(note)',
      '周期天数(cycle_day)',
    ],
  },
  BODY_LOG: {
    name: SHEETS_NAMES.BODY_LOG,
    fields: [
      'body_log_id',
      'logged_at',
      'weight_kg',
      'bmi',
      'body_fat_pct',
      'lean_body_mass_kg',
      'source',
      'note',
    ],
    headers: [
      '身体记录ID(body_log_id)',
      '记录时间(logged_at)',
      '体重公斤(weight_kg)',
      'BMI(bmi)',
      '体脂率(body_fat_pct)',
      '瘦体重公斤(lean_body_mass_kg)',
      '数据来源(source)',
      '备注(note)',
    ],
  },
  SLEEP_LOG: {
    name: SHEETS_NAMES.SLEEP_LOG,
    fields: [
      'sleep_log_id',
      'logged_at',
      'sleep_start_at',
      'sleep_end_at',
      'sleep_hours',
      'sleep_quality',
      'source',
      'note',
    ],
    headers: [
      '睡眠记录ID(sleep_log_id)',
      '记录时间(logged_at)',
      '睡眠开始时间(sleep_start_at)',
      '睡眠结束时间(sleep_end_at)',
      '睡眠时长小时(sleep_hours)',
      '睡眠质量(sleep_quality)',
      '数据来源(source)',
      '备注(note)',
    ],
  },
  WORKOUT_LOG: {
    name: SHEETS_NAMES.WORKOUT_LOG,
    fields: [
      'workout_id',
      'logged_at',
      'workout_name',
      'workout_video_url',
      'workout_level',
      'duration_min',
      'avg_hr',
      'max_hr',
      'min_hr',
      'calories_kcal',
      'note',
    ],
    headers: [
      '运动ID(workout_id)',
      '记录时间(logged_at)',
      '运动名称(workout_name)',
      '运动视频链接(workout_video_url)',
      '运动等级(workout_level)',
      '运动时长分钟(duration_min)',
      '平均心率(avg_hr)',
      '最高心率(max_hr)',
      '最低心率(min_hr)',
      '消耗卡路里(calories_kcal)',
      '备注(note)',
    ],
  },
  STOCK: {
    name: SHEETS_NAMES.STOCK,
    fields: [
      'stock_item_id',
      'item_name',
      'quantity',
      'unit',
      'purchased_at',
      'updated_at',
      'purchase_channel',
      'linked_food_ref_id',
      'note',
    ],
    headers: [
      '库存ID(stock_item_id)',
      '食材名称(item_name)',
      '当前数量(quantity)',
      '单位(unit)',
      '购入日期(purchased_at)',
      '更新时间(updated_at)',
      '购买渠道(purchase_channel)',
      '关联热量参考ID(linked_food_ref_id)',
      '备注(note)',
    ],
  },
  FOOD_LOG: {
    name: SHEETS_NAMES.FOOD_LOG,
    fields: [
      'food_log_id',
      'logged_at',
      'meal_type',
      'meal_text',
      'estimated_calories',
      'parse_status',
      'note',
    ],
    headers: [
      '饮食记录ID(food_log_id)',
      '记录时间(logged_at)',
      '餐次类型(meal_type)',
      '饮食内容(meal_text)',
      '估算热量(estimated_calories)',
      'AI拆解状态(parse_status)',
      '备注(note)',
    ],
  },
  FOOD_ITEMS: {
    name: SHEETS_NAMES.FOOD_ITEMS,
    fields: [
      'parent_food_log_id',
      'item_name',
      'quantity',
      'unit',
      'estimated_calories',
      'linked_food_ref_id',
      'linked_stock_item_id',
      'ai_confidence',
      'note',
    ],
    headers: [
      '父饮食记录ID(parent_food_log_id)',
      '项目名称(item_name)',
      '数量(quantity)',
      '单位(unit)',
      '估算热量(estimated_calories)',
      '关联热量参考ID(linked_food_ref_id)',
      '关联库存ID(linked_stock_item_id)',
      'AI置信度(ai_confidence)',
      '备注(note)',
    ],
  },
  BOT_LOG: {
    name: SHEETS_NAMES.BOT_LOG,
    fields: ['logged_at', 'raw_text', 'handling_mode', 'status', 'note'],
    headers: [
      '记录时间(logged_at)',
      '原始输入(raw_text)',
      '处理方式(handling_mode)',
      '处理结果(status)',
      '备注(note)',
    ],
  },
  REF_CALORIES: {
    name: SHEETS_NAMES.REF_CALORIES,
    fields: [
      'food_ref_id',
      'food_name',
      'brand',
      'serving_size',
      'serving_unit',
      'calories_kcal',
      'protein_g',
      'fat_g',
      'carbs_g',
      'source',
      'updated_at',
      'note',
    ],
    headers: [
      '热量参考ID(food_ref_id)',
      '食物名称(food_name)',
      '品牌(brand)',
      '份量数值(serving_size)',
      '份量单位(serving_unit)',
      '热量千卡(calories_kcal)',
      '蛋白质克(protein_g)',
      '脂肪克(fat_g)',
      '碳水克(carbs_g)',
      '数据来源(source)',
      '更新时间(updated_at)',
      '备注(note)',
    ],
  },
} as const;
