import { GEMINI_API_KEY, GEMINI_MODEL } from '../../app-config';
import { TOOL_REGISTRY } from '../../tools/registry';
import type {
  GenericToolRequest,
  GenericToolResult,
  ToolRecord,
  ToolSelector,
} from '../../tools/types';

type GeminiFunctionCall = {
  id?: string;
  name?: string;
  args?: Record<string, unknown>;
};

type GeminiPart = {
  text?: string;
  functionCall?: GeminiFunctionCall;
  functionResponse?: {
    id?: string;
    name: string;
    response: Record<string, unknown>;
  };
  [key: string]: unknown;
};

export type GeminiContent = {
  role?: string;
  parts?: GeminiPart[];
  [key: string]: unknown;
};

type GeminiResponse = {
  candidates?: Array<{
    content?: GeminiContent;
    finishReason?: string;
  }>;
  promptFeedback?: {
    blockReason?: string;
  };
};

export type AiStartResponse =
  | {
      mode: 'reply';
      reply: string;
      modelContent: GeminiContent;
    }
  | {
      mode: 'tool';
      request: GenericToolRequest;
      functionCall: {
        id?: string;
        name: 'readData' | 'insertData' | 'updateData';
        args: Record<string, unknown>;
      };
      modelContent: GeminiContent;
    };

function getGeminiUrl(): string {
  return `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${GEMINI_API_KEY}`;
}

function listSheetsForOperation(
  operation: 'read' | 'insert' | 'update',
): string[] {
  return Object.entries(TOOL_REGISTRY)
    .filter(([, entry]) =>
      entry.schema.tooling.allowedOperations.includes(operation),
    )
    .map(([sheet]) => sheet)
    .sort();
}

function listSelectorsForOperation(operation: 'read' | 'update'): string[] {
  return Array.from(
    new Set(
      Object.values(TOOL_REGISTRY)
        .filter((entry) =>
          entry.schema.tooling.allowedOperations.includes(operation),
        )
        .flatMap((entry) => entry.schema.tooling.allowedSelectors),
    ),
  ).sort();
}

function buildToolCatalog(): string {
  return Object.entries(TOOL_REGISTRY)
    .map(([sheet, entry]) => {
      const fields = entry.schema.fields
        .map((field) => {
          const flags = [
            field.tooling?.autoGenerated ? 'auto-generated' : '',
            field.tooling?.immutable ? 'immutable' : '',
          ].filter(Boolean);

          return flags.length > 0
            ? `${field.key}(${flags.join(',')})`
            : field.key;
        })
        .join(', ');

      return `- ${sheet}: operations=${entry.schema.tooling.allowedOperations.join(',')}; selectors=${entry.schema.tooling.allowedSelectors.join(',')}; fields=${fields}`;
    })
    .join('\n');
}

function buildSystemInstruction(): string {
  return [
    'You are HaijiSan, a personal health, nutrition, and logging assistant.',
    'Your primary perspective is health management, nutrition management, recovery, sleep, exercise, and sustainable daily habits.',
    'Use function calls when the user wants to read or write spreadsheet data.',
    'If the user asks a health or nutrition question that depends on their own history, current status, or recent logs, prefer calling readData first before answering.',
    'If there is no clear need to read or write spreadsheet data, answer directly and mainly from the perspective of health management and nutrition management.',
    'If the request is ambiguous, ask a concise follow-up question instead of guessing missing arguments.',
    'Do not overclaim, do not pretend to diagnose disease, and stay practical and specific.',
    'For updateData, never invent a row number. Use readData first or ask the user for clarification.',
    'Available sheets and fields:',
    buildToolCatalog(),
  ].join('\n\n');
}

function buildFunctionDeclarations(): Array<Record<string, unknown>> {
  return [
    {
      name: 'readData',
      description:
        "Read spreadsheet records. Use this before answering personalized health or nutrition questions when you need the user's own history or recent logs.",
      parameters: {
        type: 'object',
        properties: {
          sheet: {
            type: 'string',
            enum: listSheetsForOperation('read'),
            description: 'Target sheet key to read from.',
          },
          selectorType: {
            type: 'string',
            enum: listSelectorsForOperation('read'),
            description:
              'Selector type. Use date, date-range, recent, or row-number depending on the sheet and task.',
          },
          date: {
            type: 'string',
            description: 'YYYY-MM-DD when selectorType is date.',
          },
          startDate: {
            type: 'string',
            description: 'YYYY-MM-DD when selectorType is date-range.',
          },
          endDate: {
            type: 'string',
            description: 'YYYY-MM-DD when selectorType is date-range.',
          },
          limit: {
            type: 'integer',
            description: 'Positive integer when selectorType is recent.',
          },
          referenceDate: {
            type: 'string',
            description:
              'Optional ISO date-time anchor when selectorType is recent.',
          },
          rowNumber: {
            type: 'integer',
            description: 'Sheet row number when selectorType is row-number.',
          },
          fields: {
            type: 'array',
            items: {
              type: 'string',
            },
            description:
              'Optional list of field keys to project in the read result.',
          },
        },
        required: ['sheet', 'selectorType'],
      },
    },
    {
      name: 'insertData',
      description:
        'Insert one spreadsheet record. Only use this when the user clearly asked to log or create data.',
      parameters: {
        type: 'object',
        properties: {
          sheet: {
            type: 'string',
            enum: listSheetsForOperation('insert'),
            description: 'Target sheet key to insert into.',
          },
          record: {
            type: 'object',
            description:
              'Flat JSON object containing field keys and values for the target sheet. Do not include auto-generated fields.',
          },
        },
        required: ['sheet', 'record'],
      },
    },
    {
      name: 'updateData',
      description:
        'Update one spreadsheet row. Only use this when the exact target row is known.',
      parameters: {
        type: 'object',
        properties: {
          sheet: {
            type: 'string',
            enum: listSheetsForOperation('update'),
            description: 'Target sheet key to update.',
          },
          rowNumber: {
            type: 'integer',
            description: 'Exact sheet row number to update.',
          },
          updates: {
            type: 'object',
            description:
              'Flat JSON object containing only the fields to change. Do not include immutable or auto-generated fields.',
          },
        },
        required: ['sheet', 'rowNumber', 'updates'],
      },
    },
  ];
}

function callGemini(payload: Record<string, unknown>): GeminiResponse {
  const response = UrlFetchApp.fetch(getGeminiUrl(), {
    method: 'post',
    contentType: 'application/json',
    muteHttpExceptions: true,
    payload: JSON.stringify(payload),
  });
  const status = response.getResponseCode();
  const body = response.getContentText();

  if (status < 200 || status >= 300) {
    throw new Error(`Gemini request failed (${status}): ${body}`);
  }

  return JSON.parse(body) as GeminiResponse;
}

function extractCandidateContent(response: GeminiResponse): GeminiContent {
  const content = response.candidates?.[0]?.content;

  if (content) {
    return content;
  }

  if (response.promptFeedback?.blockReason) {
    throw new Error(
      `Gemini blocked request: ${response.promptFeedback.blockReason}`,
    );
  }

  const finishReason = response.candidates?.[0]?.finishReason;

  throw new Error(
    finishReason
      ? `Gemini returned no content. finishReason=${finishReason}`
      : 'Gemini returned no content.',
  );
}

function extractText(content: GeminiContent): string {
  return (content.parts ?? [])
    .map((part) => (typeof part.text === 'string' ? part.text : ''))
    .join('')
    .trim();
}

function extractFunctionCall(
  content: GeminiContent,
): GeminiFunctionCall | undefined {
  return (content.parts ?? []).find((part) => Boolean(part.functionCall))
    ?.functionCall;
}

function getRequiredString(args: Record<string, unknown>, key: string): string {
  const value = args[key];

  if (typeof value !== 'string' || !value.trim()) {
    throw new Error(`Function argument ${key} must be a non-empty string.`);
  }

  return value;
}

function getOptionalString(
  args: Record<string, unknown>,
  key: string,
): string | undefined {
  const value = args[key];

  return typeof value === 'string' && value.trim() ? value : undefined;
}

function getRequiredInteger(
  args: Record<string, unknown>,
  key: string,
): number {
  const value = args[key];

  if (typeof value !== 'number' || !Number.isInteger(value)) {
    throw new Error(`Function argument ${key} must be an integer.`);
  }

  return value;
}

function getOptionalStringArray(
  args: Record<string, unknown>,
  key: string,
): string[] | undefined {
  const value = args[key];

  if (value === undefined) {
    return undefined;
  }

  if (!Array.isArray(value) || value.some((item) => typeof item !== 'string')) {
    throw new Error(`Function argument ${key} must be a string array.`);
  }

  const result: string[] = [];

  value.forEach((item) => {
    result.push(item as string);
  });

  return result;
}

function getRequiredRecord(
  args: Record<string, unknown>,
  key: string,
): ToolRecord {
  const value = args[key];

  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error(`Function argument ${key} must be an object.`);
  }

  return value as ToolRecord;
}

function buildReadSelector(args: Record<string, unknown>): ToolSelector {
  const selectorType = getRequiredString(args, 'selectorType');

  switch (selectorType) {
    case 'date':
      return {
        type: 'date',
        date: getRequiredString(args, 'date'),
      };
    case 'date-range':
      return {
        type: 'date-range',
        startDate: getRequiredString(args, 'startDate'),
        endDate: getRequiredString(args, 'endDate'),
      };
    case 'recent':
      return {
        type: 'recent',
        limit: getRequiredInteger(args, 'limit'),
        referenceDate: getOptionalString(args, 'referenceDate'),
      };
    case 'row-number':
      return {
        type: 'row-number',
        rowNumber: getRequiredInteger(args, 'rowNumber'),
      };
    default:
      throw new Error(`Unsupported selectorType: ${selectorType}`);
  }
}

function mapFunctionCallToRequest(
  functionCall: GeminiFunctionCall,
): GenericToolRequest {
  const name = functionCall.name;
  const args = functionCall.args;

  if (!name || !args) {
    throw new Error('Gemini functionCall must include both name and args.');
  }

  switch (name) {
    case 'readData':
      return {
        tool: 'readData',
        sheet: getRequiredString(args, 'sheet') as GenericToolRequest['sheet'],
        selector: buildReadSelector(args),
        fields: getOptionalStringArray(args, 'fields'),
      };
    case 'insertData':
      return {
        tool: 'insertData',
        sheet: getRequiredString(args, 'sheet') as GenericToolRequest['sheet'],
        record: getRequiredRecord(args, 'record'),
      };
    case 'updateData':
      return {
        tool: 'updateData',
        sheet: getRequiredString(args, 'sheet') as GenericToolRequest['sheet'],
        selector: {
          type: 'row-number',
          rowNumber: getRequiredInteger(args, 'rowNumber'),
        },
        updates: getRequiredRecord(args, 'updates'),
      };
    default:
      throw new Error(`Unsupported Gemini function name: ${name}`);
  }
}

export function startAiResponse(text: string): AiStartResponse {
  const response = callGemini({
    systemInstruction: {
      parts: [{ text: buildSystemInstruction() }],
    },
    contents: [
      {
        role: 'user',
        parts: [{ text }],
      },
    ],
    tools: [
      {
        functionDeclarations: buildFunctionDeclarations(),
      },
    ],
  });
  const modelContent = extractCandidateContent(response);
  const functionCall = extractFunctionCall(modelContent);

  if (functionCall) {
    const request = mapFunctionCallToRequest(functionCall);

    if (
      functionCall.name !== 'readData' &&
      functionCall.name !== 'insertData' &&
      functionCall.name !== 'updateData'
    ) {
      throw new Error(`Unsupported Gemini function name: ${functionCall.name}`);
    }

    return {
      mode: 'tool',
      request,
      functionCall: {
        id: functionCall.id,
        name: functionCall.name,
        args: functionCall.args ?? {},
      },
      modelContent,
    };
  }

  const reply = extractText(modelContent);

  if (!reply) {
    throw new Error('Gemini returned neither text nor functionCall.');
  }

  return {
    mode: 'reply',
    reply,
    modelContent,
  };
}

export function generateFinalAiReply(input: {
  userText: string;
  firstTurn: Extract<AiStartResponse, { mode: 'tool' }>;
  toolResult: GenericToolResult;
}): string {
  const response = callGemini({
    systemInstruction: {
      parts: [
        {
          text: `${buildSystemInstruction()}\n\nYou have already received a function result. In this turn, answer the user directly in Chinese and do not call any function again.`,
        },
      ],
    },
    contents: [
      {
        role: 'user',
        parts: [{ text: input.userText }],
      },
      input.firstTurn.modelContent,
      {
        role: 'user',
        parts: [
          {
            functionResponse: {
              id: input.firstTurn.functionCall.id,
              name: input.firstTurn.functionCall.name,
              response: {
                result: input.toolResult,
              },
            },
          },
        ],
      },
    ],
    tools: [
      {
        functionDeclarations: buildFunctionDeclarations(),
      },
    ],
    toolConfig: {
      functionCallingConfig: {
        mode: 'NONE',
      },
    },
  });
  const content = extractCandidateContent(response);

  if (extractFunctionCall(content)) {
    throw new Error(
      'Gemini returned an unexpected functionCall in the final turn.',
    );
  }

  const reply = extractText(content);

  if (!reply) {
    throw new Error('Gemini returned no final reply text.');
  }

  return reply;
}
