import { TOOL_REGISTRY } from '../../tools/registry';
import type {
  GenericToolRequest,
  GenericToolResult,
  ToolRecord,
  ToolSelector,
  ConversationTurn,
  FoodLogInsertRequest,
  GeminiContent,
  GeminiFunctionCall,
  GeminiResponse,
} from '../../types';
import { executeGeminiRequest } from './transport';
import { spreadsheetService } from '../spreadsheet';

export type AiStartResponse =
  | {
      mode: 'reply';
      reply: string;
      modelContent: GeminiContent;
    }
  | {
      mode: 'tool';
      request: GenericToolRequest | FoodLogInsertRequest;
      functionCall: {
        id?: string;
        name: 'readData' | 'insertData' | 'updateData' | 'insertFoodLog';
        args: Record<string, unknown>;
      };
      modelContent: GeminiContent;
    };

const GEMINI_RETRYABLE_STATUS_CODES = new Set([429, 500, 503]);

const GEMINI_MAX_ATTEMPTS = 3;

const GEMINI_RETRY_DELAYS_MS = [150, 300] as const;

function buildConversationContents(history: ConversationTurn[], text: string) {
  const contents: Array<{ role: string; parts: Array<{ text: string }> }> = [];

  history.forEach((turn) => {
    if (turn.userText.trim()) {
      contents.push({
        role: 'user',
        parts: [{ text: turn.userText }],
      });
    }

    if (turn.assistantText.trim()) {
      contents.push({
        role: 'model',
        parts: [{ text: turn.assistantText }],
      });
    }
  });

  contents.push({
    role: 'user',
    parts: [{ text }],
  });

  return contents;
}

function listSheetsForOperation(
  operation: 'read' | 'insert' | 'update',
): string[] {
  return Object.entries(TOOL_REGISTRY)
    .filter(([, entry]) =>
      entry.schema.tooling.allowedOperations.includes(operation),
    )
    .map(([sheet]) => sheet)
    .sort();
}

function listGenericInsertSheets(): string[] {
  return listSheetsForOperation('insert').filter(
    (sheet) => sheet !== 'FOOD_LOG',
  );
}

function listSelectorsForOperation(operation: 'read' | 'update'): string[] {
  return Array.from(
    new Set(
      Object.values(TOOL_REGISTRY)
        .filter((entry) =>
          entry.schema.tooling.allowedOperations.includes(operation),
        )
        .flatMap((entry) => entry.schema.tooling.allowedSelectors),
    ),
  ).sort();
}

function buildSchemaConstraintSummary(): string {
  return Object.entries(TOOL_REGISTRY)
    .map(([sheet, entry]) => {
      const insertRequired = entry.schema.fields
        .filter(
          (field) =>
            field.required &&
            !field.tooling?.autoGenerated &&
            !field.tooling?.immutable,
        )
        .map((field) => field.key);
      const autoGenerated = entry.schema.fields
        .filter((field) => field.tooling?.autoGenerated)
        .map((field) => field.key);
      const immutable = entry.schema.fields
        .filter((field) => field.tooling?.immutable)
        .map((field) => field.key);
      const enums = entry.schema.fields
        .filter(
          (field) =>
            field.type === 'enum' &&
            Array.isArray(field.enumValues) &&
            field.enumValues.length > 0,
        )
        .map(
          (field) => `${field.key} = ${field.enumValues?.join(' | ') ?? ''}`,
        );

      return [
        `${sheet}`,
        `ops=${entry.schema.tooling.allowedOperations.join(',')}`,
        `selectors=${entry.schema.tooling.allowedSelectors.join(',')}`,
        insertRequired.length > 0
          ? `insert-required=${insertRequired.join(',')}`
          : 'insert-required=none',
        autoGenerated.length > 0
          ? `auto=${autoGenerated.join(',')}`
          : 'auto=none',
        immutable.length > 0
          ? `immutable=${immutable.join(',')}`
          : 'immutable=none',
        enums.length > 0 ? `enums=${enums.join(';')}` : 'enums=none',
      ].join(' | ');
    })
    .join('\n');
}

function buildFieldMeaningSummary(): string {
  return Object.entries(TOOL_REGISTRY)
    .map(([sheet, entry]) => {
      const describedFields = entry.schema.fields.filter(
        (field) => field.description && !field.tooling?.autoGenerated,
      );

      if (describedFields.length === 0) {
        return null;
      }

      return `${sheet} field meanings: ${describedFields
        .map((field) => `${field.key} = ${field.description}`)
        .join('; ')}`;
    })
    .filter((line): line is string => Boolean(line))
    .join('\n');
}

function buildSystemInstruction(referenceTimestamp: Date): string {
  const currentTimestamp = spreadsheetService.getTimestamp(
    false,
    referenceTimestamp,
  );

  return [
    'You are HaijiSan, a personal health, nutrition, and logging assistant.',
    'Your primary perspective is health management, nutrition management, recovery, sleep, exercise, and sustainable daily habits.',
    'Voice and tone: calm, steady, observant, and dependable, like a seasoned long-distance team captain. Be warm but restrained, encouraging without being sugary, and practical without sounding cold.',
    'Write concise Chinese that feels composed and quietly supportive. Avoid slangy internet tone, exaggerated cheerleading, sarcasm, or melodrama.',
    'When formatting helps, never use Markdown. Use only the simplest Telegram HTML tags: <b>, <i>, and <code>. Use plain newline characters for line breaks. Do not use headings with #, fenced code blocks, Markdown links, Markdown bullet syntax, or unsupported HTML tags such as <br>.',
    `Current local timestamp for interpreting relative dates: ${currentTimestamp}.`,
    'Treat the latest user message as the primary source of truth. Use conversation history only when the latest message explicitly refers back to it with phrases such as 刚才, 那个, 继续, 改成, or similar follow-up wording. Do not repeat or reuse an older insert record when the current message clearly starts a new topic.',
    'Use function calls when the user wants to read or write spreadsheet data.',
    "When creating log records, extract the event time from the user's natural-language meaning instead of asking the app to parse it mechanically.",
    'Interpret 今天, 昨天, 前天, 本周, and other relative-date phrases against the current local timestamp above. Never invent a distant year or unrelated calendar date when the user gave a relative date like 今天.',
    'All timestamp fields must use the exact format yyyy-MM-dd HH:mm:ss.',
    'Do not output natural-language timestamp strings such as today 08:55, tomorrow morning, or similar phrases inside tool arguments.',
    'For sheets that use occurred_at, include occurred_at when the user implied a date or time such as 今天, 昨天, 早餐, 晚饭, 8:55, or similar semantic clues.',
    'If the user clearly wants to log data but did not specify an event time, it is acceptable to omit occurred_at and let the app default it to now.',
    'For FOOD_LOG inserts, always call insertFoodLog instead of insertData.',
    "insertFoodLog must include both a concise FOOD_LOG record and an items array that preserves each food item's quantity and unit from the user's wording.",
    'For FOOD_LOG, map Chinese meal words into the schema enum values: 早餐 or 早饭 -> breakfast; 午餐 or 午饭 -> lunch; 晚餐 or 晚饭 -> dinner; 加餐, 零食, 下午茶, 夜宵 -> snack unless the user clearly means a normal dinner.',
    'For SLEEP_LOG, route sleep-related statements into SLEEP_LOG rather than FOOD_LOG. Phrases like 睡眠, 睡得, 入睡, 醒来, 2:30-7:06, or 02:30 到 07:06 usually mean a sleep record with sleep_start_at, sleep_end_at, sleep_quality, and source=manual.',
    'For WORKOUT_LOG, route exercise-related statements into WORKOUT_LOG. Phrases like 跑步, 骑车, 训练, 心率, 消耗, 卡路里, or 时长 usually mean a workout record rather than food or status data.',
    'For STATUS_LOG menstruation entries, entry_type should be menstruation, cycle_day should be the numeric cycle day such as 3 for 第3天, value should hold the main status such as light, medium, or heavy bleeding, and note should keep any extra detail. Do not copy the whole sentence into value.',
    'If the user asks a health or nutrition question that depends on their own history, current status, or recent logs, prefer calling readData first before answering.',
    'If there is no clear need to read or write spreadsheet data, answer directly and mainly from the perspective of health management and nutrition management.',
    'If the request is ambiguous, ask a concise follow-up question instead of guessing missing arguments.',
    'Do not overclaim, do not pretend to diagnose disease, and stay practical and specific.',
    'For updateData, never invent a row number. Use readData first or ask the user for clarification.',
    'Schema constraints summary:',
    buildSchemaConstraintSummary(),
    'Field meaning summary:',
    buildFieldMeaningSummary(),
  ].join('\n\n');
}

function buildFunctionDeclarations(): Array<Record<string, unknown>> {
  return [
    {
      name: 'readData',
      description:
        "Read spreadsheet records. Use this before answering personalized health or nutrition questions when you need the user's own history or recent logs.",
      parameters: {
        type: 'object',
        properties: {
          sheet: {
            type: 'string',
            enum: listSheetsForOperation('read'),
            description: 'Target sheet key to read from.',
          },
          selectorType: {
            type: 'string',
            enum: listSelectorsForOperation('read'),
            description:
              'Selector type. Use date, date-range, recent, or row-number depending on the sheet and task.',
          },
          date: {
            type: 'string',
            description: 'YYYY-MM-DD when selectorType is date.',
          },
          startDate: {
            type: 'string',
            description: 'YYYY-MM-DD when selectorType is date-range.',
          },
          endDate: {
            type: 'string',
            description: 'YYYY-MM-DD when selectorType is date-range.',
          },
          limit: {
            type: 'integer',
            description: 'Positive integer when selectorType is recent.',
          },
          referenceDate: {
            type: 'string',
            description:
              'Optional ISO date-time anchor when selectorType is recent.',
          },
          rowNumber: {
            type: 'integer',
            description: 'Sheet row number when selectorType is row-number.',
          },
          fields: {
            type: 'array',
            items: {
              type: 'string',
            },
            description:
              'Optional list of field keys to project in the read result.',
          },
        },
        required: ['sheet', 'selectorType'],
      },
    },
    {
      name: 'insertData',
      description:
        'Insert one spreadsheet record. Only use this when the user clearly asked to log or create data.',
      parameters: {
        type: 'object',
        properties: {
          sheet: {
            type: 'string',
            enum: listGenericInsertSheets(),
            description: 'Target sheet key to insert into.',
          },
          record: {
            type: 'object',
            description:
              "Flat JSON object containing field keys and values for the target sheet. Do not include auto-generated fields. All timestamp values must use the exact format yyyy-MM-dd HH:mm:ss. Never pass natural-language timestamp strings like today 08:55. For event-log sheets, infer occurred_at from the user's natural-language meaning whenever possible; if no event time was provided, occurred_at may be omitted and the app will default it to now. Do not use insertData for FOOD_LOG; use insertFoodLog instead. For SLEEP_LOG, put the sleep interval into sleep_start_at and sleep_end_at, map sleep quality into good, normal, or poor, and use source=manual for user-entered text. For WORKOUT_LOG, use workout_name, workout_level, duration_min, heart-rate fields, and calories_kcal instead of putting exercise details into other sheets.",
          },
        },
        required: ['sheet', 'record'],
      },
    },
    {
      name: 'insertFoodLog',
      description:
        'Insert one FOOD_LOG record together with structured meal items. Use this for all food logging requests.',
      parameters: {
        type: 'object',
        properties: {
          record: {
            type: 'object',
            description:
              'Flat FOOD_LOG record containing field keys and values. Do not include auto-generated fields. meal_type must be exactly one of breakfast, lunch, dinner, snack. meal_text should be a concise summary of what was eaten. All timestamp values must use the exact format yyyy-MM-dd HH:mm:ss.',
          },
          items: {
            type: 'array',
            description:
              "Structured meal items for downstream nutrition and stock resolution. Preserve the user's quantity and unit instead of flattening everything into one serving.",
            items: {
              type: 'object',
              properties: {
                itemName: {
                  type: 'string',
                  description: 'Food item name.',
                },
                quantity: {
                  type: 'number',
                  description: 'Positive quantity for the item.',
                },
                unit: {
                  type: 'string',
                  description:
                    'Unit that matches the user wording, such as g, ml, piece, bowl, cup, 份, 个.',
                },
              },
              required: ['itemName', 'quantity', 'unit'],
            },
          },
        },
        required: ['record', 'items'],
      },
    },
    {
      name: 'updateData',
      description:
        'Update one spreadsheet row. Only use this when the exact target row is known.',
      parameters: {
        type: 'object',
        properties: {
          sheet: {
            type: 'string',
            enum: listSheetsForOperation('update'),
            description: 'Target sheet key to update.',
          },
          rowNumber: {
            type: 'integer',
            description: 'Exact sheet row number to update.',
          },
          updates: {
            type: 'object',
            description:
              'Flat JSON object containing only the fields to change. Do not include immutable or auto-generated fields. All timestamp values must use the exact format yyyy-MM-dd HH:mm:ss.',
          },
        },
        required: ['sheet', 'rowNumber', 'updates'],
      },
    },
  ];
}

function callGemini(payload: Record<string, unknown>): GeminiResponse {
  return executeGeminiRequest<GeminiResponse>(payload, {
    retryableStatusCodes: GEMINI_RETRYABLE_STATUS_CODES,
    retryDelaysMs: GEMINI_RETRY_DELAYS_MS,
    maxAttempts: GEMINI_MAX_ATTEMPTS,
    failureLabel: 'Gemini request',
  });
}

function extractCandidateContent(response: GeminiResponse): GeminiContent {
  const content = response.candidates?.[0]?.content;

  if (content) {
    return content;
  }

  if (response.promptFeedback?.blockReason) {
    throw new Error(
      `Gemini blocked request: ${response.promptFeedback.blockReason}`,
    );
  }

  const finishReason = response.candidates?.[0]?.finishReason;

  throw new Error(
    finishReason
      ? `Gemini returned no content. finishReason=${finishReason}`
      : 'Gemini returned no content.',
  );
}

function extractText(content: GeminiContent): string {
  return (content.parts ?? [])
    .map((part) => (typeof part.text === 'string' ? part.text : ''))
    .join('')
    .trim();
}

function extractFunctionCall(
  content: GeminiContent,
): GeminiFunctionCall | undefined {
  return (content.parts ?? []).find((part) => Boolean(part.functionCall))
    ?.functionCall;
}

function getRequiredString(args: Record<string, unknown>, key: string): string {
  const value = args[key];

  if (typeof value !== 'string' || !value.trim()) {
    throw new Error(`Function argument ${key} must be a non-empty string.`);
  }

  return value;
}

function getOptionalString(
  args: Record<string, unknown>,
  key: string,
): string | undefined {
  const value = args[key];

  return typeof value === 'string' && value.trim() ? value : undefined;
}

function getRequiredInteger(
  args: Record<string, unknown>,
  key: string,
): number {
  const value = args[key];

  if (typeof value !== 'number' || !Number.isInteger(value)) {
    throw new Error(`Function argument ${key} must be an integer.`);
  }

  return value;
}

function getOptionalStringArray(
  args: Record<string, unknown>,
  key: string,
): string[] | undefined {
  const value = args[key];

  if (value === undefined) {
    return undefined;
  }

  if (!Array.isArray(value) || value.some((item) => typeof item !== 'string')) {
    throw new Error(`Function argument ${key} must be a string array.`);
  }

  const result: string[] = [];

  value.forEach((item) => {
    result.push(item as string);
  });

  return result;
}

function getRequiredRecord(
  args: Record<string, unknown>,
  key: string,
): ToolRecord {
  const value = args[key];

  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error(`Function argument ${key} must be an object.`);
  }

  return value as ToolRecord;
}

function getRequiredFoodLogItems(
  args: Record<string, unknown>,
  key: string,
): FoodLogInsertRequest['items'] {
  const value = args[key];

  if (!Array.isArray(value)) {
    throw new Error(`Function argument ${key} must be an array.`);
  }

  return value.map((item, index) => {
    if (typeof item !== 'object' || item === null || Array.isArray(item)) {
      throw new Error(`Function argument ${key}[${index}] must be an object.`);
    }

    const itemRecord = item as Record<string, unknown>;
    const itemName = getRequiredString(itemRecord, 'itemName');
    const quantity = itemRecord.quantity;
    const unit = getRequiredString(itemRecord, 'unit');

    if (
      typeof quantity !== 'number' ||
      !Number.isFinite(quantity) ||
      quantity <= 0
    ) {
      throw new Error(
        `Function argument ${key}[${index}].quantity must be a positive number.`,
      );
    }

    return {
      itemName,
      quantity,
      unit,
    };
  });
}

function buildReadSelector(args: Record<string, unknown>): ToolSelector {
  const selectorType = getRequiredString(args, 'selectorType');

  switch (selectorType) {
    case 'date':
      return {
        type: 'date',
        date: getRequiredString(args, 'date'),
      };
    case 'date-range':
      return {
        type: 'date-range',
        startDate: getRequiredString(args, 'startDate'),
        endDate: getRequiredString(args, 'endDate'),
      };
    case 'recent':
      return {
        type: 'recent',
        limit: getRequiredInteger(args, 'limit'),
        referenceDate: getOptionalString(args, 'referenceDate'),
      };
    case 'row-number':
      return {
        type: 'row-number',
        rowNumber: getRequiredInteger(args, 'rowNumber'),
      };
    default:
      throw new Error(`Unsupported selectorType: ${selectorType}`);
  }
}

function mapFunctionCallToRequest(
  functionCall: GeminiFunctionCall,
): GenericToolRequest | FoodLogInsertRequest {
  const name = functionCall.name;
  const args = functionCall.args;

  if (!name || !args) {
    throw new Error('Gemini functionCall must include both name and args.');
  }

  switch (name) {
    case 'readData':
      return {
        tool: 'readData',
        sheet: getRequiredString(args, 'sheet') as GenericToolRequest['sheet'],
        selector: buildReadSelector(args),
        fields: getOptionalStringArray(args, 'fields'),
      };
    case 'insertData':
      return {
        tool: 'insertData',
        sheet: getRequiredString(args, 'sheet') as GenericToolRequest['sheet'],
        record: getRequiredRecord(args, 'record'),
      };
    case 'insertFoodLog':
      return {
        tool: 'insertFoodLog',
        sheet: 'FOOD_LOG',
        record: getRequiredRecord(args, 'record'),
        items: getRequiredFoodLogItems(args, 'items'),
      };
    case 'updateData':
      return {
        tool: 'updateData',
        sheet: getRequiredString(args, 'sheet') as GenericToolRequest['sheet'],
        selector: {
          type: 'row-number',
          rowNumber: getRequiredInteger(args, 'rowNumber'),
        },
        updates: getRequiredRecord(args, 'updates'),
      };
    default:
      throw new Error(`Unsupported Gemini function name: ${name}`);
  }
}

export function startAiResponse(
  text: string,
  conversationHistory: ConversationTurn[] = [],
  referenceTimestamp: Date = new Date(),
): AiStartResponse {
  const response = callGemini({
    systemInstruction: {
      parts: [{ text: buildSystemInstruction(referenceTimestamp) }],
    },
    contents: buildConversationContents(conversationHistory, text),
    tools: [
      {
        functionDeclarations: buildFunctionDeclarations(),
      },
    ],
  });
  const modelContent = extractCandidateContent(response);
  const functionCall = extractFunctionCall(modelContent);

  if (functionCall) {
    const request = mapFunctionCallToRequest(functionCall);

    if (
      functionCall.name !== 'readData' &&
      functionCall.name !== 'insertFoodLog' &&
      functionCall.name !== 'insertData' &&
      functionCall.name !== 'updateData'
    ) {
      throw new Error(`Unsupported Gemini function name: ${functionCall.name}`);
    }

    return {
      mode: 'tool',
      request,
      functionCall: {
        id: functionCall.id,
        name: functionCall.name,
        args: functionCall.args ?? {},
      },
      modelContent,
    };
  }

  const reply = extractText(modelContent);

  if (!reply) {
    throw new Error('Gemini returned neither text nor functionCall.');
  }

  return {
    mode: 'reply',
    reply,
    modelContent,
  };
}

export function generateFinalAiReply(input: {
  userText: string;
  conversationHistory?: ConversationTurn[];
  referenceTimestamp: Date;
  firstTurn: Extract<AiStartResponse, { mode: 'tool' }>;
  toolResult: GenericToolResult;
}): string {
  const response = callGemini({
    systemInstruction: {
      parts: [
        {
          text: `${buildSystemInstruction(input.referenceTimestamp)}\n\nYou have already received a function result. In this turn, answer the user directly in Chinese and do not call any function again. Keep the same calm HaijiSan tone. If formatting helps, use only simple HTML tags and never Markdown.`,
        },
      ],
    },
    contents: [
      ...buildConversationContents(
        input.conversationHistory ?? [],
        input.userText,
      ),
      input.firstTurn.modelContent,
      {
        role: 'user',
        parts: [
          {
            functionResponse: {
              id: input.firstTurn.functionCall.id,
              name: input.firstTurn.functionCall.name,
              response: {
                result: input.toolResult,
              },
            },
          },
        ],
      },
    ],
    tools: [
      {
        functionDeclarations: buildFunctionDeclarations(),
      },
    ],
    toolConfig: {
      functionCallingConfig: {
        mode: 'NONE',
      },
    },
  });
  const content = extractCandidateContent(response);

  if (extractFunctionCall(content)) {
    throw new Error(
      'Gemini returned an unexpected functionCall in the final turn.',
    );
  }

  const reply = extractText(content);

  if (!reply) {
    throw new Error('Gemini returned no final reply text.');
  }

  return reply;
}
