import { spreadsheetService } from '../services/spreadsheet';
import {
  matchesRecordDate,
  matchesRecordDateRange,
} from '../shared/date-reference';
import { mapRowToRecord } from '../shared/record-mapper';
import { listRecentEntries } from '../shared/record-query';
import { createTimestampedEntryId, formatLoggedAt } from '../shared/records';
import type { SheetSchema } from '../types';
import type {
  GenericToolRequest,
  GenericToolResult,
  InsertDataRequest,
  InsertDataResult,
  ReadDataRequest,
  ReadDataResult,
  RuntimeRow,
  ToolRecord,
  ToolRegistryEntry,
  ToolSelector,
  ToolSheetKey,
  UpdateDataRequest,
  UpdateDataResult,
} from './types';
import { TOOL_REGISTRY, getStringRecordValue } from './registry';
import { getFieldByKey, validateGenericToolRequest } from './validation';

function assertValidRequest(request: GenericToolRequest): void {
  const errors = validateGenericToolRequest(request);

  if (errors.length > 0) {
    throw new Error(errors.join(' '));
  }
}

function getDefaultEventTimeKey(
  schema: SheetSchema,
  entry: ToolRegistryEntry,
): string {
  if (entry.eventTimeKey) {
    return entry.eventTimeKey;
  }

  if (schema.fields.some((field) => field.key === 'updated_at')) {
    return 'updated_at';
  }

  return 'logged_at';
}

function getSortValue(entry: ToolRegistryEntry, record: ToolRecord): string {
  if (entry.sortValue) {
    return entry.sortValue(record);
  }

  const key = getDefaultEventTimeKey(entry.schema, entry);
  const value = record[key];

  return typeof value === 'string' ? value : '';
}

function matchesDateForEntry(
  entry: ToolRegistryEntry,
  record: ToolRecord,
  dateStamp: string,
): boolean {
  if (entry.matchesDate) {
    return entry.matchesDate(record, dateStamp);
  }

  return matchesRecordDate(
    getSortValue(entry, record),
    getStringRecordValue(record, 'note'),
    dateStamp,
  );
}

function matchesDateRangeForEntry(
  entry: ToolRegistryEntry,
  record: ToolRecord,
  startDateStamp: string,
  endDateStamp: string,
): boolean {
  if (entry.matchesDateRange) {
    return entry.matchesDateRange(record, startDateStamp, endDateStamp);
  }

  return matchesRecordDateRange(
    getSortValue(entry, record),
    getStringRecordValue(record, 'note'),
    startDateStamp,
    endDateStamp,
  );
}

function listRuntimeRows(sheet: ToolSheetKey): RuntimeRow[] {
  const entry = TOOL_REGISTRY[sheet];

  return spreadsheetService
    .getDataRows(entry.schema.name)
    .map(({ rowNumber, values }) => ({
      rowNumber,
      record: mapRowToRecord<ToolRecord>(
        spreadsheetService,
        entry.schema,
        values,
      ),
    }));
}

function sortRows(
  rows: RuntimeRow[],
  entry: ToolRegistryEntry,
  direction: 'asc' | 'desc',
): RuntimeRow[] {
  return [...rows].sort((left, right) => {
    const leftValue = getSortValue(entry, left.record);
    const rightValue = getSortValue(entry, right.record);

    return direction === 'asc'
      ? leftValue.localeCompare(rightValue)
      : rightValue.localeCompare(leftValue);
  });
}

function selectRows(sheet: ToolSheetKey, selector: ToolSelector): RuntimeRow[] {
  const entry = TOOL_REGISTRY[sheet];
  const rows = listRuntimeRows(sheet);

  switch (selector.type) {
    case 'row-number':
      return rows.filter((row) => row.rowNumber === selector.rowNumber);
    case 'date':
      return sortRows(
        rows.filter((row) =>
          matchesDateForEntry(entry, row.record, selector.date),
        ),
        entry,
        'asc',
      );
    case 'date-range':
      return sortRows(
        rows.filter((row) =>
          matchesDateRangeForEntry(
            entry,
            row.record,
            selector.startDate,
            selector.endDate,
          ),
        ),
        entry,
        'asc',
      );
    case 'recent':
      return listRecentEntries({
        entries: rows,
        limit: selector.limit,
        sortValue: (row) => getSortValue(entry, row.record),
        referenceDate: selector.referenceDate
          ? new Date(selector.referenceDate)
          : undefined,
        getEntryTime: (row) =>
          new Date(getSortValue(entry, row.record)).getTime(),
      });
  }
}

function projectRecord(record: ToolRecord, fields?: string[]): ToolRecord {
  if (!fields || fields.length === 0) {
    return record;
  }

  return Object.fromEntries(
    fields.map((field) => [field, record[field] ?? '']),
  );
}

function applyRuntimeInsertDefaults(
  entry: ToolRegistryEntry,
  record: ToolRecord,
  timestamp: Date,
): ToolRecord {
  const schema = entry.schema;
  const nextRecord: ToolRecord = { ...record };

  schema.fields.forEach((field) => {
    if (field.tooling?.autoGenerated && nextRecord[field.key] === undefined) {
      if (!schema.idPrefix) {
        throw new Error(`No idPrefix configured for ${schema.name}`);
      }

      nextRecord[field.key] = createTimestampedEntryId(
        spreadsheetService,
        schema.idPrefix,
        timestamp,
      );
    }

    if (field.key === 'logged_at' && nextRecord[field.key] === undefined) {
      nextRecord[field.key] = formatLoggedAt(spreadsheetService, timestamp);
    }

    if (field.key === 'updated_at' && nextRecord[field.key] === undefined) {
      nextRecord[field.key] = formatLoggedAt(spreadsheetService, timestamp);
    }
  });

  if (
    entry.eventTimeKey &&
    nextRecord[entry.eventTimeKey] === undefined &&
    schema.fields.some((field) => field.key === entry.eventTimeKey)
  ) {
    nextRecord[entry.eventTimeKey] = formatLoggedAt(
      spreadsheetService,
      timestamp,
    );
  }

  return nextRecord;
}

function applyRuntimeUpdateDefaults(
  schema: SheetSchema,
  updates: ToolRecord,
  timestamp: Date,
): ToolRecord {
  const nextUpdates: ToolRecord = { ...updates };

  if (
    schema.fields.some((field) => field.key === 'updated_at') &&
    nextUpdates.updated_at === undefined
  ) {
    const updatedAtField = getFieldByKey(schema, 'updated_at');

    if (!updatedAtField?.tooling?.immutable) {
      nextUpdates.updated_at = formatLoggedAt(spreadsheetService, timestamp);
    }
  }

  return nextUpdates;
}

export function executeReadData(request: ReadDataRequest): ReadDataResult {
  assertValidRequest(request);

  return {
    tool: 'readData',
    sheet: request.sheet,
    selector: request.selector,
    rows: selectRows(request.sheet, request.selector).map((row) => ({
      rowNumber: row.rowNumber,
      record: projectRecord(row.record, request.fields),
    })),
  };
}

export function executeInsertData(
  request: InsertDataRequest,
  timestamp: Date = new Date(),
): InsertDataResult {
  assertValidRequest(request);

  const entry = TOOL_REGISTRY[request.sheet];
  const record = applyRuntimeInsertDefaults(entry, request.record, timestamp);

  entry.table.insert(record);

  return {
    tool: 'insertData',
    sheet: request.sheet,
    record,
  };
}

export function executeUpdateData(
  request: UpdateDataRequest,
  timestamp: Date = new Date(),
): UpdateDataResult {
  assertValidRequest(request);

  const entry = TOOL_REGISTRY[request.sheet];
  const updates = applyRuntimeUpdateDefaults(
    entry.schema,
    request.updates,
    timestamp,
  );

  entry.table.updateAtRow(request.selector.rowNumber, updates);

  return {
    tool: 'updateData',
    sheet: request.sheet,
    selector: request.selector,
    updates,
  };
}

export function executeGenericToolRequest(
  request: GenericToolRequest,
  timestamp?: Date,
): GenericToolResult {
  switch (request.tool) {
    case 'readData':
      return executeReadData(request);
    case 'insertData':
      return executeInsertData(request, timestamp);
    case 'updateData':
      return executeUpdateData(request, timestamp);
  }
}
