import type {
  FieldSchema,
  SheetSchema,
  ToolOperation,
  ToolSelectorType,
} from '../types';
import type {
  GenericToolRequest,
  InsertDataRequest,
  ReadDataRequest,
  ToolRecord,
  UpdateDataRequest,
} from './types';
import { TOOL_REGISTRY } from './registry';

export function getFieldByKey(
  schema: SheetSchema,
  key: string,
): FieldSchema | undefined {
  return schema.fields.find((field) => field.key === key);
}

function listUnknownFieldKeys(schema: SheetSchema, keys: string[]): string[] {
  return keys.filter((key) => !getFieldByKey(schema, key));
}

function isOperationAllowed(
  schema: SheetSchema,
  operation: ToolOperation,
): boolean {
  return schema.tooling.allowedOperations.includes(operation);
}

function isSelectorAllowed(
  schema: SheetSchema,
  selectorType: ToolSelectorType,
): boolean {
  return schema.tooling.allowedSelectors.includes(selectorType);
}

function validateRequestedFields(
  schema: SheetSchema,
  fields?: string[],
): string[] {
  if (!fields || fields.length === 0) {
    return [];
  }

  return listUnknownFieldKeys(schema, fields).map(
    (field) => `Unknown field for ${schema.name}: ${field}`,
  );
}

function validateRecordKeys(
  schema: SheetSchema,
  record: ToolRecord,
): { unknownKeys: string[]; fields: FieldSchema[] } {
  const keys = Object.keys(record);
  const unknownKeys = listUnknownFieldKeys(schema, keys);
  const fields = keys
    .map((key) => getFieldByKey(schema, key))
    .filter((field): field is FieldSchema => Boolean(field));

  return { unknownKeys, fields };
}

export function validateReadDataRequest(request: ReadDataRequest): string[] {
  const schema = TOOL_REGISTRY[request.sheet].schema;
  const errors: string[] = [];

  if (!isOperationAllowed(schema, 'read')) {
    errors.push(`Sheet ${request.sheet} does not allow readData.`);
  }

  if (!isSelectorAllowed(schema, request.selector.type)) {
    errors.push(
      `Sheet ${request.sheet} does not allow selector type ${request.selector.type}.`,
    );
  }

  return errors.concat(validateRequestedFields(schema, request.fields));
}

export function validateInsertDataRequest(
  request: InsertDataRequest,
): string[] {
  const schema = TOOL_REGISTRY[request.sheet].schema;
  const errors: string[] = [];

  if (!isOperationAllowed(schema, 'insert')) {
    errors.push(`Sheet ${request.sheet} does not allow insertData.`);
  }

  const { unknownKeys, fields } = validateRecordKeys(schema, request.record);

  errors.push(
    ...unknownKeys.map(
      (field) => `Unknown field for ${request.sheet}: ${field}`,
    ),
  );
  errors.push(
    ...fields
      .filter((field) => field.tooling?.autoGenerated)
      .map(
        (field) =>
          `Field ${field.key} on ${request.sheet} is auto-generated and cannot be provided.`,
      ),
  );

  return errors;
}

export function validateUpdateDataRequest(
  request: UpdateDataRequest,
): string[] {
  const schema = TOOL_REGISTRY[request.sheet].schema;
  const errors: string[] = [];

  if (!isOperationAllowed(schema, 'update')) {
    errors.push(`Sheet ${request.sheet} does not allow updateData.`);
  }

  if (!isSelectorAllowed(schema, request.selector.type)) {
    errors.push(
      `Sheet ${request.sheet} does not allow selector type ${request.selector.type}.`,
    );
  }

  const { unknownKeys, fields } = validateRecordKeys(schema, request.updates);

  errors.push(
    ...unknownKeys.map(
      (field) => `Unknown field for ${request.sheet}: ${field}`,
    ),
  );
  errors.push(
    ...fields
      .filter((field) => field.tooling?.autoGenerated)
      .map(
        (field) =>
          `Field ${field.key} on ${request.sheet} is auto-generated and cannot be updated.`,
      ),
  );
  errors.push(
    ...fields
      .filter((field) => field.tooling?.immutable)
      .map(
        (field) =>
          `Field ${field.key} on ${request.sheet} is immutable and cannot be updated.`,
      ),
  );

  return errors;
}

export function validateGenericToolRequest(
  request: GenericToolRequest,
): string[] {
  switch (request.tool) {
    case 'readData':
      return validateReadDataRequest(request);
    case 'insertData':
      return validateInsertDataRequest(request);
    case 'updateData':
      return validateUpdateDataRequest(request);
  }
}
